import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — MotherLode CMI",
  description: "Terms of service for MotherLode CMI.",
};

export default function TermsPage() {
  return (
    <main className="relative min-h-screen text-text">
      <header className="sticky top-0 z-50 backdrop-blur bg-ink/70 border-b border-white/5">
        <nav className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3 group">
            <div className="w-8 h-8 rounded bg-gradient-to-br from-gold to-copper flex items-center justify-center">
              <span className="text-ink font-bold text-sm">M</span>
            </div>
            <span className="font-semibold tracking-tight">MotherLode CMI</span>
          </Link>
          <Link href="/" className="text-sm text-muted hover:text-text transition-colors">← Back to home</Link>
        </nav>
      </header>

      <article className="max-w-3xl mx-auto px-6 py-20 prose-content">
        <p className="text-sm text-muted uppercase tracking-wider mb-4">Legal</p>
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">Terms of Service</h1>
        <p className="text-muted mb-12">Effective Date: May 24, 2026</p>

        <Section title="1. Acceptance of Terms">
          <p>
            These Terms of Service (the &quot;Terms&quot;) govern your access to and use of the MotherLode CMI website at motherlodecmi.com and any related software, services, applications, demonstrations, and content (collectively, the &quot;Services&quot;) operated by Lucid Tech LLC (&quot;Lucid Tech,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By accessing or using the Services, you agree to be bound by these Terms. If you do not agree, do not use the Services.
          </p>
        </Section>

        <Section title="2. Eligibility">
          <p>
            The Services are intended for use by program managers, state geological surveys, university researchers, operators in the critical-minerals sector, and other qualified institutional users. You represent that you are at least eighteen years of age and have the authority to enter into these Terms on behalf of yourself and any organization you represent.
          </p>
        </Section>

        <Section title="3. Intellectual Property">
          <p>
            The MotherLode CMI platform, including all software, models, datasets, content, designs, logos, and the methods underlying its operation, is the property of Lucid Tech LLC or its licensors. Multiple novel mechanisms within the platform are protected by one or more pending U.S. patent applications. Nothing in these Terms grants you any right, title, or interest in the platform or its intellectual property other than the limited right to access and use the Services as expressly permitted.
          </p>
        </Section>

        <Section title="4. Restricted Demo and Confidentiality">
          <p>
            The Services include restricted-access demonstrations available only to invited users with credentials issued by Lucid Tech. You agree not to share access credentials, reproduce, screenshot, record, distribute, or disclose the demonstration content to any third party without written permission. Any content marked or identified as confidential is the confidential information of Lucid Tech and may not be used for any purpose other than evaluation of the Services.
          </p>
        </Section>

        <Section title="5. Acceptable Use">
          <p>
            You agree to use the Services only for lawful purposes and in accordance with these Terms. You will not:
          </p>
          <ul>
            <li>Reverse engineer, decompile, or attempt to derive the source of any part of the platform</li>
            <li>Use the Services to develop a competing product, model, or dataset</li>
            <li>Scrape, harvest, or programmatically extract data without express written permission</li>
            <li>Misrepresent your identity or the institution you represent</li>
            <li>Interfere with the security, integrity, or performance of the Services</li>
          </ul>
        </Section>

        <Section title="6. Data and Outputs">
          <p>
            Outputs generated by the Services (predictions, reports, confidence intervals, and other analytical content) are provided for informational and decision-support purposes only. They do not constitute professional engineering, geological, legal, or financial advice. You are solely responsible for verifying outputs and for any decisions or actions you take based on them.
          </p>
        </Section>

        <Section title="7. Disclaimer of Warranties">
          <p>
            THE SERVICES ARE PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS. TO THE FULLEST EXTENT PERMITTED BY LAW, LUCID TECH DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT, ACCURACY, AND UNINTERRUPTED AVAILABILITY.
          </p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>
            TO THE FULLEST EXTENT PERMITTED BY LAW, LUCID TECH AND ITS AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUES, DATA, OR BUSINESS OPPORTUNITIES, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICES. OUR AGGREGATE LIABILITY FOR ANY CLAIM ARISING OUT OF THESE TERMS SHALL NOT EXCEED ONE HUNDRED U.S. DOLLARS.
          </p>
        </Section>

        <Section title="9. Indemnification">
          <p>
            You agree to defend, indemnify, and hold harmless Lucid Tech LLC and its officers, directors, employees, agents, and affiliates from any claims, damages, liabilities, costs, and expenses (including reasonable attorneys&apos; fees) arising out of or related to your use of the Services or your breach of these Terms.
          </p>
        </Section>

        <Section title="10. Termination">
          <p>
            We may suspend or terminate your access to the Services at any time, with or without cause and with or without notice. Upon termination, all rights granted to you under these Terms will immediately cease. Sections that by their nature should survive termination (including Intellectual Property, Confidentiality, Disclaimers, Limitation of Liability, and Indemnification) will survive.
          </p>
        </Section>

        <Section title="11. Governing Law">
          <p>
            These Terms are governed by the laws of the State of Delaware, United States, without regard to its conflict of laws principles. Any dispute arising out of or related to these Terms shall be resolved in the state or federal courts located in Delaware, and you consent to the exclusive jurisdiction and venue of those courts.
          </p>
        </Section>

        <Section title="12. Changes to These Terms">
          <p>
            We may update these Terms from time to time. The effective date at the top of this page reflects the most recent revision. Material changes will be reasonably communicated. Your continued use of the Services after changes take effect constitutes acceptance of the revised Terms.
          </p>
        </Section>

        <Section title="13. Contact">
          <p>
            Questions about these Terms can be directed to <a href="mailto:info@webdesignpros365.com" className="text-gold hover:underline">info@webdesignpros365.com</a>.
          </p>
        </Section>
      </article>

      <Footer />
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl md:text-2xl font-bold tracking-tight mb-4 text-gold">{title}</h2>
      <div className="text-light text-base leading-relaxed space-y-4 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-2 [&_a]:text-gold [&_a]:hover:underline">
        {children}
      </div>
    </section>
  );
}

function Footer() {
  return (
    <footer className="border-t border-white/5 mt-10">
      <div className="max-w-6xl mx-auto px-6 py-10 text-center">
        <div className="text-sm text-muted mb-2">
          MotherLode CMI is a product of <a href="https://lucidtechlabsllc.com" className="text-gold hover:underline">Lucid Tech LLC</a>.
        </div>
        <div className="text-xs text-muted">
          © {new Date().getFullYear()} Lucid Tech LLC. All rights reserved. U.S. Provisional Patent Application Filed.
        </div>
        <div className="text-xs text-muted mt-4 flex items-center justify-center gap-4">
          <Link href="/terms" className="hover:text-gold transition-colors">Terms of Service</Link>
          <span>·</span>
          <Link href="/privacy" className="hover:text-gold transition-colors">Privacy Policy</Link>
          <span>·</span>
          <Link href="/disclosures" className="hover:text-gold transition-colors">Disclosures</Link>
        </div>
      </div>
    </footer>
  );
}
